services:
  redis:
    image: redis:latest
    volumes:
      - ./data/redis:/data
    ports:
      - "6379:6379"
    networks:
      - internal

  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    networks:
      - internal

  chat:
    build:
      context: .
      dockerfile: ./cmd/chat/Dockerfile
    volumes:
      - type: bind
        source: ./data/sqlite/jackal.sqlite
        target: ${SQLITE_PATH}
        read_only: false
    environment:
      - SQLITE_PATH=${SQLITE_PATH}
      - REDIS_URL=${REDIS_URL}
      - RABBIT_URL=${RABBIT_URL}
    ports:
      - "8081:8080"
    networks:
      - internal

  notify:
    build:
      context: .
      dockerfile: ./cmd/notify/Dockerfile
    volumes:
      - type: bind
        source: ./data/sqlite/jackal.sqlite
        target: ${SQLITE_PATH}
        read_only: false
    environment:
      - SQLITE_PATH=${SQLITE_PATH}
      - REDIS_URL=${REDIS_URL}
      - RABBIT_URL=${RABBIT_URL}
    ports:
      - "8082:8080"
    networks:
      - internal

networks:
  internal:

volumes:
  pulsardata:
  pulsarconf:
  rabbitmqdata: